### ISSUE TITLE
Use the code in my homework?

### ISSUE THREAD

**Issue by nkxxll** [chm0dx/peepedIn#1]
## Asking for permission to use your code in a university homework

Hey, @chm0dx I'm writing a homework for university on the topic OSINT and found your script on my search for OSINT-tools. Since there is no licence for this project, I thought I'd rather ask whether I could use your script as an example for a LinkedIn scraper. I hope that's OK? I'm looking forward to your response!

Really like the simplicity of the script, great project! :+1:

**Comment by chm0dx** [comment]
Absolutely! Glad to help. 

Best of luck with your assignment.

**Comment by nkxxll** [comment]
Thank you very much!!! :+1:  <3
